# Default values for divvycloud.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
imageName: divvycloud/divvycloud:latest
imagePullPolicy: Always

# DATABASE CONFIG #

# Uncomment this section if you want to use an exteranl database.
# Please ensure that both divvy and divvykeys shecmas exist and 
# that the user has permissions on both schemas

useExternalDb: false
# If you would like to use an CloudSQLProxy for GKE please provide the CloudSQLInstanceName and
# the kubernetes secret name for the service account creds
# IMPORTANT : You may either provide a cloudSQLInstanceName or databaseHost , but not both
# If you supply both - things will not work properly

# Use GKE

# CloudSQLProxy will also look for a secret called cloudsql-db-credentials
#cloudSQLInstanceName: divvycloud-engineering:us-east1:divvycloud-cluster-1-sql

##OR

# Native MySQL
#databaseHost: 10.128.0.7


# If you are not using CloudSQL, please provide the hostname/IP address for the remote MySQL
databasePort: "3306"

# Please provide the username and password
databaseUser: divvy
databasePassword: divvy

# STORAGE #
#  We will use a PVC for the MySQL db.
#  If your kubernetes cluster does not support PVC, please change pvcEnabled to false
pvcEnabled: true
storageSize: 30Gi

# END OF DATABASE CONFIG #


## INGRESS

## Comment the below section if you want to run without an ingress rule
#
ingress:
  enabled: false
#  path: /
#  hosts:
#    - crosskube.divvycloud.io
### Uncommend the following lines if you are using an Nginx controller
#  annotations: {
#     kubernetes.io/ingress.class: nginx,
#     kubernetes.aio/tls-acme: "true"
#     }

# END OF INGRESS #

# Plugins
enablePlugins: false

# Use a GCP Internal Loadbalancer
internalLoadBalancer: true

# DivvyCloud starting scale
replicaCounts:
  harvesters: 2
  interfaceservers: 2
  schedulers: 2
  processors: 2
  longharvesters: 2
  ondemands: 2

